 <table class="table">
                    <thead>
                    <tr>
                        <th>AdminId</th>
                        <th>AdminName</th>
                        <th>Department</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>113123</td>
                        <td>MR.XXX</td>
                        <td>cse</td>
                    </tr>
                    <tr>
                        <td>113123</td>
                        <td>MR.XXX</td>
                        <td>cse</td>
                    </tr>
                    <tr>
                        <td>113123</td>
                        <td>MR.XXX</td>
                        <td>cse</td>
                    </tr>
                    <tr>
                        <td>113123</td>
                        <td>MR.XXX</td>
                        <td>cse</td>
                    </tr>
                    <tr>
                        <td>113123</td>
                        <td>MR.XXX</td>
                        <td>cse</td>
                    </tr>
                    <tr>
                        <td>113123</td>
                        <td>MR.XXX</td>
                        <td>cse</td>
                    </tr>
                    <tr>
                        <td>113123</td>
                        <td>MR.XXX</td>
                        <td>cse</td>
                    </tr>
                    <tr>
                        <td>113123</td>
                        <td>MR.XXX</td>
                        <td>cse</td>
                    </tr>
                    </tbody>
                </table>
    </div>

